# Generated by Django 5.2.7 on 2025-10-21 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="taprofile",
            name="display_name",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
