# Generated by Django 5.2.5 on 2025-10-21 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="age",
        ),
    ]
